In [24]:
import sqlite3
import pandas as pd


cnx = sqlite3.connect('../corona-sniffer/backend/data/database.db')

df_agents = pd.read_sql_query("SELECT * FROM agents", cnx)
df_contacts = pd.read_sql_query("SELECT * FROM contacts", cnx)
df_walks = pd.read_sql_query("SELECT * FROM walks", cnx)
df_walkers = pd.read_sql_query("SELECT * FROM walkers", cnx)
df_pairs = pd.read_sql_query("SELECT * from pairs", cnx)

In [36]:
%load_ext autoreload
%autoreload 2

from utils import * 
from draw import *
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

### TraceTogether

In [27]:
walkers = df_walkers['id'].tolist()
resolved_walkers = df_walkers.loc[df_walkers['resolved'] == 1]
print("# Walkers: {}".format(len(walkers)))
print("# Infected Walkers: {}".format(len(resolved_walkers)))

walks = df_walks[['walker_id', 'time']].values.tolist()
print("# Walks: {}".format(len(walks)))

pairs = df_pairs.values.tolist()
print("# Contact Pairs: {}".format(len(pairs)))

# Walkers: 300
# Infected Walkers: 18
# Walks: 60000
# Contact Pairs: 1224

In [60]:
df_walks.head()

    walker_id time                 x                  y
0  5aba88d1ab    2  335.359388392862  -1816.52434409847
1  5aba88d1ab    3  346.678915929492  -1800.74717961911
2  5aba88d1ab    4  357.608798047294  -1784.88456337222
3  5aba88d1ab    5  370.613422850043  -1770.46843209417
4  5aba88d1ab    6   381.89882263859  -1756.10840419182

In [95]:
T = 50
contacted_pairs = [[] for _ in range(T)]
dic = {}
idx = 0
for id1, id2, time, distance in pairs:
    if int(time) >= T:
        continue
        
    contacted_pairs[int(time)].append((id1, id2, float(distance)))

In [96]:
triangles = get_triangles(contacted_pairs)
print(triangles)

[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [['80675969b6', 'a7ca81a42b', '8b1f2ee8dc']], [], [], [], [], [], [], [], [], [], [], [], [], [], [['f7e0053f1c', 'a8a7328c52', '7a03fbbdf2']], [], [], [], [], [], [], [], [], [], [], [], [], []]

In [97]:
fixed_points_arr, random_points_arr = [], []

for i in range(T):
    df = pd.DataFrame(contacted_pairs[i], columns=['i', 'j', 'distance'])
    fixed_points, random_points = {}, {}

    def cmp(tri_a, tri_b):
        count_a = sum([1 if p in fixed_points else 0 for p in tri_a])
        count_b = sum([1 if p in fixed_points else 0 for p in tri_b])
        if count_a - count_b == 0:
            return sum([1 if p in random_points else 0 for p in tri_a]) - sum([1 if p in random_points else 0 for p in tri_b])
        else:
            return count_a - count_b

    idx_count = collections.Counter()
    for a, b, c in triangles[i]:
        idx_count[a] += 1
        idx_count[b] += 1
        idx_count[c] += 1

    sorted_triangles = sorted(triangles[i], key=functools.cmp_to_key(cmp))

    for p in contacted_pairs[i][:5]:
        walker_id, time, x, y = df_walks.loc[(df_walks['walker_id'] == p[0]) & (df_walks['time'] == str(i))].values[0]
        fixed_points[walker_id] = (float(x), float(y))
        walker_id, time, x, y = df_walks.loc[(df_walks['walker_id'] == p[1]) & (df_walks['time'] == str(i))].values[0]
        fixed_points[walker_id] = (float(x), float(y))
    print(f'Known points: {len(fixed_points)}')

    while len(sorted_triangles) != 0:
        a, b, c = sorted_triangles.pop()
        if a in fixed_points and b in fixed_points and c in fixed_points:
            continue
        # have 2 fixed points
        if (a in fixed_points and b in fixed_points) or (a in fixed_points and c in fixed_points) or (b in fixed_points and c in fixed_points):
            pass
        else:
            break

        if a in fixed_points:
            if b not in fixed_points:
                a, b = b, a
            else:
                a, c = c, a
        x1, y1 = fixed_points[b]
        x2, y2 = fixed_points[c]
        bc = retrieve_distance(df, b, c)
        ac = retrieve_distance(df, a, c)
        ab = retrieve_distance(df, a, b)
        degree, _, _ = get_degrees(abs(y2-y1), bc, abs(x2-x1), (b, c, np.linalg.norm([x1-x2, y1-y2]))) #np.arccos(max(-1, min(np.dot([1, 0], [(x2 - x1) / bc, (y2 - y1) / bc]), 1)))
        degree_a, degree_b, degree_c = get_degrees(bc, ac, ab, 2)
        tmp = []
        factors = [[1, 1], [1, -1], [-1, 1], [-1, -1]]
        # if y1 < y2:
        for fx, fy in factors:
            x, y = fx * np.cos(degree - degree_b) * ab + x1, fy * np.sin(degree - degree_b) * ab + y1
            if (abs(np.linalg.norm([x2-x, y2-y]) - ac) < 1e-5):
                tmp.append((x, y))
        for fx, fy in factors:
            x, y = fx * np.cos(degree + degree_b) * ab + x1, fy * np.sin(degree + degree_b) * ab + y1
            if (abs(np.linalg.norm([x2 - x, y2 - y]) - ac) < 1e-5):
                tmp.append((x, y))
        # else:
        for fx, fy in factors:
            x, y = fx * np.cos(degree - degree_c) * ac + x2, fy * np.sin(degree - degree_c) * ac + y2
            if (abs(np.linalg.norm([x2 - x, y2 - y]) - ab) < 1e-5):
                tmp.append((x, y))
        for fx, fy in factors:
            x, y = fx * np.cos(degree + degree_c) * ac + x2, fy * np.sin(degree + degree_c) * ac + y2
            if (abs(np.linalg.norm([x2 - x, y2 - y]) - ab) < 1e-5):
                tmp.append((x, y))

        if a in random_points and random_points[a] is not None:
            fixed = False
            for x, y in random_points[a]:
                for xt, yt in tmp:
                    if x == xt and y == yt:
                        fixed_points[a] = (x, y)
                        fixed = True
                        random_points[a] = None
                        break
            if not fixed:
                random_points[a] += tmp
        else:
            random_points[a] = tmp
        sorted_triangles = sorted(sorted_triangles, key=functools.cmp_to_key(cmp))
    print(f'Total points: {len(contacted_pairs[i])}, Fixed points: {len(fixed_points)}, Random points: {len(random_points)}')

    fixed_points_arr.append(fixed_points)
    random_points_arr.append(random_points)

Known points: 7
Total points: 14, Fixed points: 7, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 8
Total points: 10, Fixed points: 8, Random points: 0
Known points: 6
Total points: 12, Fixed points: 6, Random points: 0
Known points: 8
Total points: 10, Fixed points: 8, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0
Known points: 6
Total points: 8, Fixed points: 6, Random points: 0
Known points: 8
Total points: 14, Fixed points: 8, Random points: 0
Known points: 8
Total points: 10, Fixed points: 8, Random points: 0
Known points: 6
Total points: 12, Fixed points: 6, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0
Known points: 8
Total points: 16, Fixed points: 8, Random points: 0
Known points: 8
Total points: 18, Fixed points: 8, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0
Known points: 8
Total points: 20, Fixed points: 8, Random points: 0
Known points: 8
Total points: 18, Fixed points: 8, Random points: 0
Known points: 8
Total points: 16, Fixed points: 8, Random points: 0
Known points: 6
Total points: 10, Fixed points: 6, Random points: 0
Known points: 7
Total points: 12, Fixed points: 7, Random points: 0
Known points: 8
Total points: 14, Fixed points: 8, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 2
Total points: 2, Fixed points: 2, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 6
Total points: 10, Fixed points: 6, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 6
Total points: 8, Fixed points: 6, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 8
Total points: 10, Fixed points: 8, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0
Known points: 8
Total points: 18, Fixed points: 8, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0
Known points: 10
Total points: 16, Fixed points: 10, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 8
Total points: 8, Fixed points: 8, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 4
Total points: 4, Fixed points: 4, Random points: 0
Known points: 6
Total points: 6, Fixed points: 6, Random points: 0
Known points: 6
Total points: 8, Fixed points: 6, Random points: 0
Known points: 8
Total points: 12, Fixed points: 8, Random points: 0

In [98]:
for t in range(T):
    count, rand_count = 0, 0
    distance = 0
    
    for id1, id2, time, distance in pairs:
        if int(time) >= T:
            continue
    
        if id1 in fixed_points_arr[t] or :
            count += 1
            distance += np.linalg.norm([x - fixed_points_arr[t][i][0], y - fixed_points_arr[t][i][1]])
        elif i in random_points_arr[t]:
            rand_count += 1

    print(f'Matched: {count}/{N}, Random: {rand_count}/{N}, Average error distance: {distance / count if count != 0 else None}')

SyntaxError: invalid syntax (<ipython-input-98-96cbd0d3c5fe>, line 9)

### DP3T

In [16]:
agents = df_agents['id'].tolist()
print("# Agents (Devices): {}".format(len(agents)))

contacts = df_contacts['rolling_id'].tolist()
resolved_contacts = df_contacts.loc[df_contacts['resolved_id'].notnull()]
print("# Contacts: {}".format(len(contacts)))
print("# Resolved Contacts: {}".format(len(resolved_contacts)))

# Agents (Devices): 374
# Contacts: 3113
# Resolved Contacts: 148

In [17]:
import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="",
  database="anon_btlog"
)

mycursor = mydb.cursor()

df = pd.read_sql_query("SELECT * FROM anon_logdata", mydb)

In [19]:
df.head(30)

,index,Address,Time,Date,Day,Search,Session,Person
0,1,000000000000,0 days 17:10:29,2005-10-31,Mon,1,1,c6c5992d7d4c0d51827a56e3dff9f310
1,2,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:10:31,2005-10-31,Mon,1,1,c6c5992d7d4c0d51827a56e3dff9f310
2,3,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:10:59,2005-10-31,Mon,2,1,c6c5992d7d4c0d51827a56e3dff9f310
3,4,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:11:29,2005-10-31,Mon,3,1,c6c5992d7d4c0d51827a56e3dff9f310
4,5,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:12:00,2005-10-31,Mon,4,1,c6c5992d7d4c0d51827a56e3dff9f310
5,6,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:12:30,2005-10-31,Mon,5,1,c6c5992d7d4c0d51827a56e3dff9f310
6,7,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:13:00,2005-10-31,Mon,6,1,c6c5992d7d4c0d51827a56e3dff9f310
7,8,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:13:30,2005-10-31,Mon,7,1,c6c5992d7d4c0d51827a56e3dff9f310
8,9,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:14:00,2005-10-31,Mon,8,1,c6c5992d7d4c0d51827a56e3dff9f310
9,10,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:14:30,2005-10-31,Mon,9,1,c6c5992d7d4c0d51827a56e3dff9f310
10,11,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:15:00,2005-10-31,Mon,10,1,c6c5992d7d4c0d51827a56e3dff9f310
11,12,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:15:30,2005-10-31,Mon,11,1,c6c5992d7d4c0d51827a56e3dff9f310
12,13,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:16:00,2005-10-31,Mon,12,1,c6c5992d7d4c0d51827a56e3dff9f310
13,14,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:16:30,2005-10-31,Mon,13,1,c6c5992d7d4c0d51827a56e3dff9f310
14,15,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:17:00,2005-10-31,Mon,14,1,c6c5992d7d4c0d51827a56e3dff9f310
15,16,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:17:30,2005-10-31,Mon,15,1,c6c5992d7d4c0d51827a56e3dff9f310
16,17,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:17:43,2005-10-31,Mon,15,1,c6c5992d7d4c0d51827a56e3dff9f310
17,18,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:18:00,2005-10-31,Mon,16,1,c6c5992d7d4c0d51827a56e3dff9f310
18,19,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:18:00,2005-10-31,Mon,16,1,c6c5992d7d4c0d51827a56e3dff9f310
19,20,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:18:32,2005-10-31,Mon,17,1,c6c5992d7d4c0d51827a56e3dff9f310
20,21,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:18:32,2005-10-31,Mon,17,1,c6c5992d7d4c0d51827a56e3dff9f310
21,22,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:19:01,2005-10-31,Mon,18,1,c6c5992d7d4c0d51827a56e3dff9f310
22,23,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:19:01,2005-10-31,Mon,18,1,c6c5992d7d4c0d51827a56e3dff9f310
23,24,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:19:30,2005-10-31,Mon,19,1,c6c5992d7d4c0d51827a56e3dff9f310
24,25,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:19:30,2005-10-31,Mon,19,1,c6c5992d7d4c0d51827a56e3dff9f310
25,26,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:20:03,2005-10-31,Mon,20,1,c6c5992d7d4c0d51827a56e3dff9f310
26,27,8d08a7e5e9c5ada5457effcb18b52878,0 days 17:20:03,2005-10-31,Mon,20,1,c6c5992d7d4c0d51827a56e3dff9f310
27,28,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:20:30,2005-10-31,Mon,21,1,c6c5992d7d4c0d51827a56e3dff9f310
28,29,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:21:00,2005-10-31,Mon,22,1,c6c5992d7d4c0d51827a56e3dff9f310
29,30,96dbec31c17d68e38ec48406ffa99a8d,0 days 17:21:30,2005-10-31,Mon,23,1,c6c5992d7d4c0d51827a56e3dff9f310